version: '3.1'

services:
  yapi:
    image: registrys/yapi
    restart: always
    ports:
      - 3000:3000
    volumes:
      - "./yapi/config.json:/yapi/config.json"
      - "./yapi/init.lock:/yapi/init.lock"
      - "./log/:/yapi/log/"